USE [Gestran_Teste]
GO

CREATE VIEW VIEW_TOTAIS
AS
	SELECT
	V.Vendedor,
	SUM(CAST(V.Valor_da_Venda AS DECIMAL(15,2))) AS TOTAL_VENDAS,
	SUM(CAST(V.Valor_do_Desconto AS DECIMAL(15,2))) AS TOTAL_DESCONTOS,
	SUM(CAST(V.Valor_Total AS DECIMAL(15,2))) AS TOTAL_LIQUIDO
	FROM vendas V
	GROUP BY
	V.Vendedor
GO

CREATE VIEW VIEW_MENOR_COMISSAO
AS
	SELECT
	MIN(TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
	FROM [dbo].[VIEW_TOTAIS]
GO

CREATE VIEW VIEW_MAIOR_COMISSAO
AS
	SELECT
	MAX(TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
	FROM [dbo].[VIEW_TOTAIS]
GO

CREATE FUNCTION [dbo].[FN_COMISSAO](@ValorBase DECIMAL(10,2), @Percent DECIMAL(10,2))
RETURNS DECIMAL(10,2)
AS
BEGIN
	DECLARE @com DECIMAL(10,2)
	
	SELECT @com = (@Percent/100)*@ValorBase
	IF (@com IS NULL)
		SET @com = 0;
	RETURN @com
END
GO

CREATE FUNCTION FN_TOTAIS (@DTINI DATE, @DTFIM DATE)
RETURNS TABLE
AS
RETURN 
(
	SELECT
	V.Vendedor,
	SUM(CAST(V.Valor_da_Venda AS DECIMAL(15,2))) AS TOTAL_VENDAS,
	SUM(CAST(V.Valor_do_Desconto AS DECIMAL(15,2))) AS TOTAL_DESCONTOS,
	SUM(CAST(V.Valor_Total AS DECIMAL(15,2))) AS TOTAL_LIQUIDO
	FROM vendas V
	WHERE V.DATA BETWEEN @DTINI AND @DTFIM
	GROUP BY
	V.Vendedor
)
GO